// Autogenerated by Hanako


import { Debug } from '../../views/ts/components/Debug';
import { LazyLoader } from '../../views/ts/components/LazyLoader';
import { Menu } from '../../views/twig/components/Menu/index';
import { RGPDConsent } from '../../views/twig/components/RGPDConsent/index'; 


(new Debug()).init();
(new LazyLoader()).init();
(new Menu()).init();
(new RGPDConsent()).init(); 
