// Autogenerated by Hanako

import { Debug } from './components/Debug';
import { LazyLoader } from './components/LazyLoader';

import { Menu } from '../../views/twig/components/Menu';
import { RGPDConsent } from '../../views/twig/components/RGPDConsent'; 

(new Debug()).init();
(new LazyLoader()).init();

(new Menu()).init();
(new RGPDConsent()).init(); 
